version: '3.1'

services:
    db:
        container_name: db
        image: mysql:5.7.31
        restart: always
        ports:
            - '32224:3306'
        environment:
            MYSQL_DATABASE: GKTECHNICALTEST
            MYSQL_ROOT_PASSWORD: example
            MYSQL_USER: gktest
            MYSQL_PASSWORD: gktest123
